/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 클랜원 목록 */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 우리 식별자. CoC 태그가 아니다 */
                memberId: string;
            };
            cookie?: never;
        };
        /** 클랜원 한 명 */
        get: operations["getMember"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 클랜원의 우리 값 수정
         * @description 우리가 정하는 값만 고친다. 이름·직책·트로피처럼 CoC 가 주인인 값은
         *     여기서 고칠 수 없다. 고쳐 봐야 다음 동기화가 되돌린다.
         *
         *     보낸 필드만 바뀐다. 보내지 않은 필드는 그대로 두고, null 을 보내면
         *     비운다.
         */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/api/v1/clans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 클랜 목록
         * @description 우리가 다루는 클랜. 지금은 미니언즈 하나뿐이다.
         *
         *     마크·레벨·점수·전적은 담지 않는다. CoC 가 주인인 값이라 우리가
         *     사본을 들고 있으면 두 곳에서 관리하게 되고 언젠가 어긋난다.
         *     필요하면 external_id 로 CoC 에 물으면 된다.
         */
        get: operations["listClans"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 우리가 이 클랜을 다루는가. CoC 가 주지 않고 우리가 판정한다.
         *     MemberStatus 와 값이 같지만 뜻이 다르다. 이쪽은 "우리 관심사인가"이고
         *     저쪽은 "클랜에 남아 있는가"다. 한쪽만 값이 늘 수 있으므로 따로 둔다.
         * @enum {string}
         */
        ClanStatus: "ACTIVE" | "INACTIVE";
        /**
         * @description CoC 가 모르는 값만 담는다. 마크·레벨·점수·전적은 CoC 가 주인이라
         *     우리가 사본을 들면 두 곳에서 관리하게 된다.
         *
         *     id 는 우리 식별자이고 externalId 는 CoC 세계의 식별자다. 주소에서
         *     '#' 을 인코딩하지 않으려고 따로 둔다.
         *
         *     이름조차 우리가 관리한다. 게임에서 클랜 이름을 바꿔도 우리 표기는
         *     그대로 둘 수 있고, 태그는 바뀌지 않으므로 그것으로 찾는다.
         */
        Clan: {
            /**
             * @description 우리 식별자(UUID 문자열)
             * @example 3f2a1b4c-5d6e-4f70-8a91-b2c3d4e5f607
             */
            id: string;
            /**
             * @description CoC 클랜 태그. 이 값으로 CoC API 를 부른다
             * @example #2C8L822LQ
             */
            externalId: string;
            /**
             * @description 우리가 붙이는 이름. 첫 동기화 때 채운다
             * @example 미니언즈
             */
            displayName?: string | null;
            status: components["schemas"]["ClanStatus"];
            /**
             * @description 처음 본 시각. ISO 8601(UTC)
             * @example 2026-09-11T07:18:57Z
             */
            createdAt: string;
            /**
             * @description 마지막으로 갱신한 시각. ISO 8601(UTC)
             * @example 2026-09-11T07:18:57Z
             */
            updatedAt: string;
        };
        ClanListResponse: {
            clans: components["schemas"]["Clan"][];
        };
        /**
         * @description 게임 안 직책. CoC API 표기를 대문자로 바꾼 값이다.
         *     ADMIN 은 게임 화면에서 "장로(Elder)"로 불린다.
         *     UNKNOWN 은 CoC 가 우리가 모르는 값을 보냈다는 뜻이다.
         * @enum {string}
         */
        ClanRole: "LEADER" | "COLEADER" | "ADMIN" | "MEMBER" | "UNKNOWN";
        /**
         * @description 리그전 선발에서의 자리. 넷 가운데 둘만 여기 담는다.
         *
         *     사람이 매기는 것 — FIXED(확정 ●), EXCLUDED(제외 ✕)
         *     계산되는 것 — 경쟁 △, 예비 ◎ 는 그 달 점수 순위가 가른다.
         *     30위 안이면 경쟁, 밖이면 예비다. 매달 바뀌므로 담지 않는다.
         *
         *     아무것도 매기지 않으면 COMPETING 이다.
         * @enum {string}
         */
        MemberGrade: "FIXED" | "COMPETING" | "EXCLUDED";
        /**
         * @description 클랜 소속 여부. CoC API 가 주지 않고 우리가 판정한다.
         *     목록에 있으면 ACTIVE, 사라지면 INACTIVE 로 내린다.
         * @enum {string}
         */
        MemberStatus: "ACTIVE" | "INACTIVE";
        /**
         * @description 클랜원 한 명. 게임 계정 하나를 가리키며 사람이 아니다.
         *
         *     id 는 우리 식별자이고 externalId 는 CoC 세계의 식별자다. 주소에서
         *     '#' 을 인코딩하지 않으려고 따로 둔다. Clan 과 같은 규칙이다.
         *
         *     grade·gradeReason·warnings·description 은 우리가 정하는 값이라
         *     동기화가 덮어쓰지 않는다.
         */
        Member: {
            /**
             * @description 우리 식별자(UUID 문자열)
             * @example 3f2a1b4c-5d6e-4f70-8a91-b2c3d4e5f607
             */
            id: string;
            /**
             * @description CoC 플레이어 태그. 이 값으로 CoC API 를 부른다
             * @example #2ABC123
             */
            externalId: string;
            name: string;
            role: components["schemas"]["ClanRole"];
            status: components["schemas"]["MemberStatus"];
            grade: components["schemas"]["MemberGrade"];
            /**
             * @description 왜 그 등급인지. "길드장", "쉬는 계정" 같은 메모
             * @example 길드장
             */
            gradeReason?: string | null;
            /**
             * @description 경고 횟수. 표시만 하고 점수에 영향을 주지 않는다
             * @default 0
             */
            warnings: number;
            townhall?: number | null;
            trophies?: number | null;
            donations?: number | null;
            donationsReceived?: number | null;
            /** @description 관리자 메모. 동기화가 덮어쓰지 않는다 */
            description?: string | null;
            /**
             * @description 처음 본 시각. ISO 8601(UTC)
             * @example 2026-09-11T07:18:57Z
             */
            createdAt: string;
            /**
             * @description 마지막으로 갱신한 시각. ISO 8601(UTC)
             * @example 2026-09-11T07:18:57Z
             */
            updatedAt: string;
        };
        /**
         * @description 클랜원에게서 우리가 정하는 값. PATCH 의 본문이다.
         *
         *     전부 선택 사항이며, 보낸 것만 바뀐다. 값을 비우려면 null 을 보낸다.
         *     하나도 보내지 않으면 고칠 것이 없으므로 거절한다.
         */
        MemberUpdate: {
            grade?: components["schemas"]["MemberGrade"];
            /**
             * @description 왜 그 등급인지. "길드장", "쉬는 계정" 같은 메모
             * @example 길드장
             */
            gradeReason?: string | null;
            /** @description 경고 횟수 */
            warnings?: number;
            /** @description 관리자 메모 */
            description?: string | null;
        };
        MemberListResponse: {
            members: components["schemas"]["Member"][];
        };
        /**
         * @description 요청을 받아들이지 못했을 때의 본문. FastAPI 가 HTTPException 을
         *     내보내는 모양과 같다.
         */
        Error: {
            /** @example 그 클랜원이 없습니다 */
            detail: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMembers: {
        parameters: {
            query?: {
                /** @description CoC 플레이어 태그로 좁힌다. '#'을 포함해 넘긴다 */
                externalId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 클랜원 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    getMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 우리 식별자. CoC 태그가 아니다 */
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 클랜원 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /** @description 그 식별자를 가진 클랜원이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 우리 식별자. CoC 태그가 아니다 */
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemberUpdate"];
            };
        };
        responses: {
            /** @description 고친 뒤의 클랜원 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
            /**
             * @description 본문이 규칙에 맞지 않다. 고칠 값을 하나도 보내지 않았거나,
             *     비울 수 없는 값(grade, warnings)에 null 을 보냈다
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 그 식별자를 가진 클랜원이 없다 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listClans: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 클랜 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanListResponse"];
                };
            };
        };
    };
}
