/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 클랜원 목록 */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 게임 안 직책. CoC API 표기를 대문자로 바꾼 값이다.
         *     ADMIN 은 게임 화면에서 "장로(Elder)"로 불린다.
         *     UNKNOWN 은 CoC 가 우리가 모르는 값을 보냈다는 뜻이다.
         * @enum {string}
         */
        ClanRole: "LEADER" | "COLEADER" | "ADMIN" | "MEMBER" | "UNKNOWN";
        /**
         * @description 클랜 소속 여부. CoC API 가 주지 않고 우리가 판정한다.
         *     목록에 있으면 ACTIVE, 사라지면 INACTIVE 로 내린다.
         * @enum {string}
         */
        MemberStatus: "ACTIVE" | "INACTIVE";
        Member: {
            /**
             * Format: uuid
             * @description 우리 식별자
             */
            id: string;
            /**
             * @description CoC 플레이어 태그
             * @example #2ABC123
             */
            tag: string;
            name: string;
            role: components["schemas"]["ClanRole"];
            status: components["schemas"]["MemberStatus"];
            townhall?: number | null;
            trophies?: number | null;
            donations?: number | null;
            donationsReceived?: number | null;
            /** @description 관리자 메모. 동기화가 덮어쓰지 않는다 */
            description?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MemberListResponse: {
            members: components["schemas"]["Member"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listMembers: {
        parameters: {
            query?: {
                /** @description 플레이어 태그로 좁힌다. '#'을 포함해 넘긴다 */
                tag?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 클랜원 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
}
